public class Calculate{  
  public integer number1 = 30;
  public integer number2 = 20;
  public integer result;
  
    public void Addition(){
         result = number1+number2;
         System.debug(result);
    }
     public void Subtraction(){
         result = number1-number2;
        System.debug(result);
    }
     public void Division(){
         result = number1/number2;
         System.debug(result);
    }
    public void Multiplication(){
         result = number1*number2;
         System.debug(result);
    }
}